version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tiktok-calculator-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tiktok_calculator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tiktok-calculator-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: tiktok-calculator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tiktok-calculator-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiktok-calculator-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tiktok_calculator?schema=public
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
    depends_on:
      - postgres
      - redis
    networks:
      - tiktok-calculator-network
    volumes:
      - ./uploads:/app/uploads

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: tiktok-calculator-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - tiktok-calculator-network

volumes:
  postgres_data:
  redis_data:

networks:
  tiktok-calculator-network:
    driver: bridge
