export const stats = {
  badge: "Stats Badge",
  title: "Platform Statistics",
  subtitle: "Key metrics and platform performance overview.",
  users: {
    label: "Users",
    description: "Total number of users using our platform."
  },
  calculations: {
    label: "Calculations",
    description: "Total number of calculations performed."
  },
  revenue: {
    label: "Revenue",
    description: "Total estimated revenue generated by users."
  },
  accuracy: {
    label: "Accuracy",
    description: "Platform calculation accuracy rate."
  },
  countries: {
    label: "Countries",
    description: "Number of countries our users come from."
  },
  uptime: {
    label: "Uptime",
    description: "Platform uptime and reliability."
  },
  platforms: {
    title: "Platform User Distribution",
    subtitle: "Breakdown of users by platform.",
    tiktok: {
      users: "TikTok Users",
      label: "TikTok",
      description: "Number of TikTok users using our calculator."
    },
    instagram: {
      users: "Instagram Users",
      label: "Instagram",
      description: "Number of Instagram users using our calculator."
    },
    youtube: {
      users: "YouTube Users",
      label: "YouTube",
      description: "Number of YouTube users using our calculator."
    }
  },
  trustIndicators: {
    rating: "Platform Rating",
    reviews: "User Reviews",
    featured: "Featured On"
  }
} as const;